### ISSUE TITLE
AttributeError: 'Pipeline' object has no attribute 'pred_dist'

### ISSUE THREAD

**Issue by astrogilda** [stanfordmlgroup/ngboost#131]
Hey!  

Let me begin by thanking y'all for a fantastic package!! I was wanting to use auto-ml (specifically, [tpot](https://epistasislab.github.io/tpot/api/)) for finding a good sklearn pipeline with ngboost as the final estimator, for a regression problem with one output variable. However, since the probabilistic prediction method is called 'pred_dist', which is not something sklearn supports, python throws an error. Do you have any suggestions?

**Comment by alejandroschuler** [comment]
Hey @astrogilda, glad you like it :)

Unfortunately there's not much we can do from the NGBoost side to make things like this work. There isn't a unified API for probabilistic regression. I'd bring it up as an issue for the auto ML package you're trying to use and see if they're interesting in supporting your use case. Otherwise you'll have to hack it together yourself.

I'll close this for now but feel free to keep the discussion going if you find anything that might be of interest to others.
