### ISSUE TITLE
Plans for R support?

### ISSUE THREAD

**Issue by AdrianAntico** [stanfordmlgroup/ngboost#14]
Are there any plans for implementing this in R?

**Comment by avati** [comment]
Hi Adrian,

I would currently put this as low priority for us. I personally am not too familiar or comfortable with R. However we would VERY MUCH welcome contributions for R integration at API level.

**Comment by AdrianAntico** [comment]
@avati What if I make it available in my R package via reticulate calls to Python for now?

**Comment by avati** [comment]
Hi @AdrianAntico, unfortunately I am not familiar with what reticulate is. Might be good to have R API be part of ngboost to keep the APIs in sync over versions. We do plan to make some simplification changes to the model creation API. Could you create a pull request so we can have a look and discuss?

**Comment by AdrianAntico** [comment]
@avati reticulate is a package in R that allows R users to call Python functions. An example of its use would be the keras pacakge in R, which is a set of reticulate bindings to call the Python functions to build those models. If you plan on making simplification changes, I can wait till the version is in a steady state before I do anything.

**Comment by avati** [comment]
The plan is to have the following new classes: ``NGBRegressor``, ``NGBClassifier``, ``NGBSurvival``  etc. in place of the current single ``NGBoost`` which takes different probability distributions and scoring rules as parameters. The new classes will just invoke ``NGBoost`` internally with the appropriate probability distribution, scoring rule and base learner. That's the simplification I was referring to. Otherwise it sounds like reticulate is just providing language bindings, and should be a fine addition/contribution!

**Comment by AdrianAntico** [comment]
@avati Thanks for the update!

**Comment by avati** [comment]
Closing this issue for now. Please re-open it if there are any updates!

**Comment by acca3003** [comment]
I have created a R version of NGBoost.
https://github.com/acca3003/ngboostR
It is a prelimiar version but you can test example.

**Comment by Akai01** [comment]
I have created an R interface which is supporting all APIs and their public methods:
https://github.com/Akai01/ngboost

**Comment by Akai01** [comment]
A forecasting package based on ngboost is available on CRAN: https://cran.r-project.org/web/packages/ngboostForecast/index.html

**Comment by Akai01** [comment]
@AdrianAntico It's a univariate time series forecasting technique. Please see the README file for further information on how to supply time series as ts objects. Univariate forecasting is faster since the base algorithm (ngboost) is single-core in nature. I'm also working on a panel version of it, but I don't expect to publish it on CRAN. The modeling strategy is as following: 

The fitted forecasting model can be formulated as following:
y = f(X) + e where X is a matrix of lags (order p) and Fourier transformation of y (in order K <=   freq/2 where freq is the frequency of y), f() is the base learner and e is the error term which is assumed to be a martingale-difference sequence (A hart assumption!). 
The reason for using Fourier transformation is to model seasonality. 

The forecasting is done recursively.

**Comment by AdrianAntico** [comment]
@Akai01 I didn't know it was a single threaded algorithm. Thanks for the heads up

**Comment by Akai01** [comment]
@AdrianAntico see https://github.com/stanfordmlgroup/ngboost/issues/156
