### ISSUE TITLE
Linear approximation for stacked ngboost models

### ISSUE THREAD

**Issue by astrogilda** [stanfordmlgroup/ngboost#146]
Hey! So I want to achieve two goals, using two sep methods:
(i) Use multiple ngboost models (trained on different pre-processed data) and output corresponding `mus` and `sigmas`. Say I use 5 models, resulting in 5 `mus` and 5 `sigmas` for all samples in the training set. I want to use just the 5 `mus` as features for a meta-learner, for which I am thinking of using yet another ngboost model since it natively outputs both mean and variance.
(ii) In addition to simple prediction, I also want to use the SHAP package for interpretability. A property of SHAP values is that you can LINEARLY combine SHAP values from different models, and the resulting sum will be accurate. In our context, this would mean finding the weights for the 5 `mus` above, and adding their SHAP values with the same weights.

However, I am faced with a dilemma. If my meta-learner is an ngboost model, then it is by definition not linear, and hence doesn't output a single weight for each feature (here feature refers to one of the 5 `mus` from the base layer of ngboost models). If I instead decide to go with a linear model, then it'll only output a `mu` and no `sigma` (aleatoric uncertainty). One compromise that I am thinking of is using ngboost as the meta-learner, fidning the average SHAP weights it assigns to the 5 features, normalizing them, and assuming that those are the weights I need to use.

Do you think this approach makes sense? If you have any suggestions or tips here, I'd be grateful!

**Comment by alejandroschuler** [comment]
Hmm, really not sure... 

Before doing anything I would make sure that adding the meta-learning actually meaningfully improves your performance by whatever metric you're using, otherwise all the rest of this is frosting on a rube goldberg machine. 

As I've mentioned here and there in the past- I'm usually pretty wary of "interpreting" these models... I'd keep the final goal in mind and think carefully about how you would judge success. For instance, when you say the resulting sum of SHAP values is "accurate", what do you mean (rhetorical question)? What real, physical quantity is it that you're trying to estimate? Perhaps adding SHAP values gives you the SHAP value you would have gotten had you calculated it directly from the meta-learner instead of just adding, but then what you're saying is that adding SHAP values accurately calculates a SHAP value, which again is perhaps nothing in reality without some strong assumptions about causality. 

Anyways, don't mean to go off on a tangent there but that's one of my favorite rants so it's easy to get me going :P

**Comment by alejandroschuler** [comment]
closing for now but feel free to keep the convo going if you have other questions
