### ISSUE TITLE
NGBoosted Ridge

### ISSUE THREAD

**Issue by anpatton** [stanfordmlgroup/ngboost#150]
Hi all - this is probably a totally fundamental misunderstanding of how NGBoost works (wouldn't be the first time), but I thought I'd ask anyway. If I use Ridge as the base learner, is there any way of extracting information about the coefficients from the fitted NGBoost object? The gross oversimplification would be `.coef_`. Thanks for putting up with my questions.

**Comment by avati** [comment]
Hi @anpatton - note that Ridge (or Lasso, or any other linear model) is not a great idea to be used as base learner with boosting techniques (not just NGBoost). That's because boosting combines the models in an additive manner, and if the base learner is linear, you still end up with a "simple" linear model that can be represented by just one set of coefficients. More technically: gradient boosting does not break out of the span of the data matrix if the base learner is linear. Boosting base learners are best when they are simple non-linear models, where adding them actually "gets you more expressivity" (such as simple decision trees).

**Comment by anpatton** [comment]
Ah yeah, that makes sense. Much appreciated.

**Comment by avati** [comment]
Closing for now
