### ISSUE TITLE
Is there support for multicore processing?

### ISSUE THREAD

**Issue by vmgustavo** [stanfordmlgroup/ngboost#156]
During executions I see a single core going up to 100% usage, is by default single core? If not how to use multiple jobs?

**Comment by alejandroschuler** [comment]
ngboost, like other boosting algorithms, does not lend itself to parallelization. There is no parallel capability at this time and I'm not sure how it would ever be. We could send different base learners to different nodes at each boosting iteration, but that would only speed up multiparameter distributions. I think xgboost has some parallelization but they acheive that with some low-level hacking of the base learners. Ngboost lets you use whatever base learners you like, so that's not an option for us.

**Comment by kmedved** [comment]
To add to what @alejandroschuler said, `Xgboost`, `LightGBM`, and Sklearn's `HistGradientBoostingClassifier `are all multiprocessed in some ways, but this is a marginal speedup at best on those libraries, and is actually leads to major slowdowns eventually, depending on the number of cores and the dimensionality of your data. Here's a useful Kaggle thread on this: https://www.kaggle.com/c/microsoft-malware-prediction/discussion/79131. More cores is not always better with GBDT models.

To the extent you have additional cores and want to speed up hyperparameter tuning, you'd usually be better off spending those resources on searching multiple sets of hyperparameters at once, such as via `RandomSearchCV`.
