### ISSUE TITLE
Question on derivatives for scoring functions

### ISSUE THREAD

**Issue by fabDav22** [stanfordmlgroup/ngboost#161]
Hello,

First, thank you for putting this package together. The methodology is a very interesting extension of the GAMLSS framework to ML and I am looking forward to using this package for applications where probabilistic predictions are desired.

In reviewing the distributional implementations with the purpose of potentially adding a distribution myself, I noticed that the derivative of the logscore for the scale parameter under the normal distribution does not seem correct.  It is currently implemented as 

D[:, 1] = 1 - ((self.loc - Y) ** 2) / self.var

but I think this should be

D[:, 1] = (1/self.scale) - ((self.loc - Y) ** 2) / (self.var*self.scale)

My conclusion of this is based off of the scipy parameterization for the normal and following the instructions you mention here https://stanfordmlgroup.github.io/ngboost/5-dev.html  of using WolframAlpha  for taking the derivative 

![image](https://user-images.githubusercontent.com/57495239/89107013-e3c7de00-d3fb-11ea-9a1e-2357b706d14b.png)

 Here the location parameter is defined as y and the scale parameter as z. I also did the work myself to double check, and the second form seems right.

Could you confirm that the gradient for the normal distribution under the logscore for the scale parameter is correct in the current implementation?

In general I am having some confusion when it comes to understanding the concept of the "internal parameterization of NGboost" vs the "user facing parameterization" when it comes to deriving the metrics and derivatives of the scores. It's not clear to me what is the benefit of using something like log(scale) rather than just scale, and it does not seem like the derivatives of the score are with respect to log(score) in some of the implemented distributions. I think some additional guidance and explanation around this concept would be helpful for developers.

Thank you in advance for the attention and help.

**Comment by alejandroschuler** [comment]
Thanks for the great question and excellent exposition @fabDav22! 

The reason that we parametrize the normal in terms of `log(scale)` instead of `scale` is that gradient descent does not respect the domain of the parameters. `scale` represents the standard deviation of the normal distribution, which we know must be positive. But if we used `scale` as the parameter internally, it is possible that a gradient descent step might result in negative values of `scale` for some or all possible values in the domain of the predictors. This is a big problem- there is no way for us to enforce that `scale(x) > 0` for all possible `x` during the fitting process. 

The way we get around that is to use `log(scale)` as the parameter. `log(scale)` can take any value it wants, which will be translated to a positive value by exponentiating. Taking this transformation is therefore how we enforce that `scale(x)>0` for all `x`. It's basically the same trick that's used to fit probabilities in logistic regression, etc: there is a prediction function that can take any real value but it is then squished through some function that maps those values to the domain of probabilities [0,1]. That is why some parameters in ngboost are internally represented as their log (or some other transformation). If the domain of the parameter is all real values (e.g. `loc` for the normal) then it is left alone. Otherwise, some invertible transformation is applied that maps between the reals and the appropriate domain. Hopefully that explains why you see this some places and not others.

Now as to your question: since ngboost is really fitting `logscale = log(scale)` and not `scale`, we need to differentiate the NLL with respect to `log(scale)` instead of `scale`. To do that, note that `scale = exp(logscale)`, plug that into the NLL, and differentiate with respect to `logscale`:

![Screen Shot 2020-08-03 at 10 43 14 AM](https://user-images.githubusercontent.com/7213095/89212232-f830e580-d577-11ea-8b2f-1730e18a3eb4.png)

^ this is your input to wolframalpha but I've let `z=e^x` so that `x` represents the `logscale` parameter.

This demonstrates that our gradient is indeed the correct gradient with respect to the log of `scale`, which is what is actually being fit. At the end of fitting, this function is exponentiated to give you the `scale` that you expect to see.

**Comment by alejandroschuler** [comment]
Hopefully this addresses the question so I'll close for now but feel free to keep the conversation going here.
