### ISSUE TITLE
Question : Regarding point estimates

### ISSUE THREAD

**Issue by anchalkhare** [stanfordmlgroup/ngboost#166]
Hi Team,

Thank you for this implementation.

Posting my question here : Why is there NA in RMSE outputs(8.94 ± NA) for Year MSD dataset for NGBoost model?

**Comment by tonyduan** [comment]
We follow the experimental procedure of 

> Each dataset is split into 20 train-test folds, except for the protein dataset which uses 5 folds and the Year Prediction MSD dataset which uses a single train-test split.

The NA arises because the Year MSD dataset only uses a single train-test split.

**Comment by anchalkhare** [comment]
Thank you for your response Tony. I have read somewhere that CV is used during training but also wanted to confirm. Is cross-validation also used for probability estimates?

**Comment by tonyduan** [comment]
Cross-validation is used to define the train/test splits that are reported in the experiments. Note that this is slightly different compared to the traditional cross-validation setting because we are not using it to select hyper-parameters. 

You can view the code for the experiments, including the cross-validation step, [[in this file]](examples/experiments/regression_exp.py).

**Comment by anchalkhare** [comment]
Gotcha. Code will certainly help me better understand training on multiple folds.

**Comment by tonyduan** [comment]
> Gotcha. Code will certainly help me better understand training on multiple folds. Seems url is incorrect. Can you check please.

@anchalkhare Whoops, not sure what happened there, here's the link
https://github.com/stanfordmlgroup/ngboost/issues/166#issuecomment-671227449
