### ISSUE TITLE
Questions about output 

### ISSUE THREAD

**Issue by chen-yu-cheng** [stanfordmlgroup/ngboost#274]
Hi, I have some questions about the output  Y_dists[0:5].params in the probabilistic regression examples. 

my question is what the 'loc' & 'scale' mean? 

thanks

![擷取](https://user-images.githubusercontent.com/65494229/127801153-65091e69-5478-402a-babc-76209a11f04b.PNG)

**Comment by alejandroschuler** [comment]
Hi @chen-yu-cheng, `loc` and `scale` refer to the parameters of the predicted normal distribution (i.e. [mu and sigma](https://en.wikipedia.org/wiki/Normal_distribution)). The parameters you get back will depend on the distribution you choose to use ngboost with.

(for future reference, you can ask these kinds of questions on the [discussions page](https://en.wikipedia.org/wiki/Normal_distribution) instead of making an issue)
