### ISSUE TITLE
Do you have any plans to support MAE for Regression problems ?

### ISSUE THREAD

**Issue by mahat** [stanfordmlgroup/ngboost#47]
MAE is popular for regression problems, current model is only using RMSE

**Comment by tonyduan** [comment]
This can be done by implementing a Laplace distribution (and its homoskedastic counterpart).

The implementation would likely not be difficult, if you or anyone else has the bandwidth to do so. Otherwise this would be nice to have but we may not around to it in the short term.

**Comment by alejandroschuler** [comment]
I think the answer to this is a little more subtle...  the current models do not use MAE (or RMSE, for that matter) because they are not optimizing for a point prediction. 

In my mind, there are two reasons you might want to use MAE instead of MSE when doing point predictions. Either 1) you want to reduce the impact of "outliers" on the fit or 2) the target of estimation is the median, not the mean. If it's #1, I'd use a distribution that has fatter tails than the normal. If it's #2, you can simply pull the median right out of the predicted conditional distribution. 

Hope that's clear, lmk if not.

**Comment by mahat** [comment]
My current concern is #1, however as far as i know we can't set the distribution which has fatter tails. converting laplace from normal can solve it ? or another way around ?

**Comment by avati** [comment]
Yes, could you please file a pull request for Laplace distribution support? Should be straightforward to implement.
