### ISSUE TITLE
Distributions for classification

### ISSUE THREAD

**Issue by srikarvaka** [stanfordmlgroup/ngboost#51]
This algorithm is working really good for regression problems where we can choose the among available distributions. However it is only limited to Bernouilli for classification which outputs a single probability value for a given outcome. Is there anyway we can have a confidence interval estimation for each possible outcome?

**Comment by alejandroschuler** [comment]
Hi there, 

The reason that only Bernoulli is available for classification is that the Bernoulli distribution is the only possible distribution for binary outcomes. 

Think about it: if you only have two possible outcomes, Y=0 or Y=1, then there are only two probabilities: p0=P(Y=0) and p1=P(Y=1), and it must be that p0+p1=1. So the distribution is basically a coin that comes up heads with probability p1, and that's exactly what the Bernoulli distribution is. It's the same if you talk about P(Y|X=x), except now you have a Bernoulli for each x, and that's what ngboost does.

I think you might be confused because ngboost is able to estimate _prediction_ intervals in the regression setting that _look_ like confidence intervals, but they are fundamentally different. 

To understand the point, let's back up and consider the difference between probabilistic prediction and standard prediction. We can also further break down "prediction" into classification, where, the outcome can only take a finite (2) number of values, and regression, where the outcome can take a continuously infinite number of values (that are arranged on the real line).

The standard prediction problem is: for an observed value of X=x, what will the most likely outcome Y be? Thus the output of standard regressors and classifiers is always a single number y representing the most likely outcome or class, denoted y=E[Y|X=x]. There are no output probabilities.

In probabilistic prediction, we are interested in the distribution over possible outcomes. That is, we want to be able to compute the probability (or relative probability) of observing any particular outcome. In the case of classification, that will be a vector of probabilities, one for each class (a probability mass function). In regression, we get a "continuous" vector of relative probabilities for each possible outcome (a probability density function). Generally speaking, we can talk about the distribution P(Y=y|X=x).

Before ngboost, it was difficult to do probabilistic _regression_ with flexible tree-based models. But it has been possible to do probabilistic _classification_ for a long time already. That's because most "classifiers" are actually _probabilistic_ classifiers in that they do return probabilities over each class. But not all do. Vanilla SVMs, for instance, do not. 

ngboost does make probabilistic classification somewhat more principled and eliminates some of the ad-hoc choices that need to be made for multi-class boosting in classification, for instance. But these improvements are largely invisible to the user, so ngboost doesn't let you "do more" relative to standard boosting when doing classification.

With that clarified, perhaps the issue of "confidence intervals" can be addressed. You would not expect a normal probabilistic classification algorithm to give you confidence intervals, so you shouldn't expect ngboost to do so either, because it's not really different in what its trying to do. 

But then why is it that we get "confidence intervals" when we use ngboost for regression? The answer is that we don't! All we get are the relative probabilities that the outcome takes each possible value. If we integrate over that distribution, it's possible to find a set of outcomes such that the outcome will fall in that set 95% of the time, but that's not a confidence interval- it's just a likely set of outcomes (more on that in a minute). Note that it's just as easy to do that with classification: let's say there are 4 classes (a,b,c,d) and their estimated probabilities (given X=x) are P(Y=a)=5%, P(Y=b)=20%, P(Y=c)=50%, P(Y=d)=25%. Then the set {b,c,d} forms a 95%-likely set of outcomes, the same way the interval [3.4, 6.11] might contain 95% of the mass of P(Y|X=x). These sets are typically called "prediction intervals" (although they don't have to be intervals, per se).

You may be looking for a "confidence interval" on the estimated probability P(Y=a). But if you want that, then why not also ask for a confidence interval for the probability estimate P(Y=5.3) in the case of regression? My point is that you are not getting confidence intervals, even when you use ngboost for regression. You can, however, extract _prediction intervals_. 

Two further notes:

1. Confidence intervals only make sense if you are treating the probabilities returned from the model as _estimates_ of some true probabilities that exist out in the "real world". In that case, you can try and figure out something about the sampling distribution of those estimates given some assumptions about the real world, and that's how you can build confidence intervals.

2. Most often the confidence intervals you will see in a regression setting are confidences on the estimate of E[Y|X=x]. Basically, assuming you rerun the model on 100 datasets, what is the distribution of values E[Y|X=x] that you get back? That's different than asking the one model what the most likely values of Y are given its estimate of P(Y|X=x), which is the prediction interval.

All that said, thanks for raising this question. I'm taking the time to thoroughly address it here because [others are confused about this as well](https://medium.com/@alejandro.schuler/hi-kyosuke-im-the-senior-author-on-the-ngboost-paper-thanks-for-your-interest-in-our-work-d52571c69aba). Do let me know if anything is unclear.

**Comment by srikarvaka** [comment]
Hi,
Thanks for explaining very clearly. We were trying to implement NGBoost code in a single machine and it was taking too long. We have approximately 10 million records to train and 4 million to validate. Are there any future plans to parallelize the computation?

**Comment by alejandroschuler** [comment]
Not as far as I know. Boosting in general is not very naturally parallelizable, but there are probably a few things we can do that we'll look into in the future.

**Comment by Shafi2016** [comment]
How can we make a prediction interval? Is there any example of it.

**Comment by tonyduan** [comment]
@Shafi2016 Does [[this issue thread]](https://github.com/stanfordmlgroup/ngboost/issues/103#issuecomment-594919649) help?

**Comment by Shafi2016** [comment]
Thanks a lot!  It helped: However, I could not fix one small issue. Though I tried to convert it another form however it did not work for me. "AttributeError: 'numpy.ndarray' object has no attribute 'scale" .This is your example code.

import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from ngboost import NGBRegressor
from ngboost.learners import default_tree_learner
from ngboost.distns import Normal
from ngboost.scores import MLE
from sklearn.ensemble import RandomForestRegressor
from lightgbm.sklearn import LGBMRegressor
from sklearn.metrics import r2_score
 
# Load data
dataset = load_boston()
X, y = dataset.data, dataset.target
features = dataset.feature_names
 
SEED = 2019
 
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.20,
                                                    random_state=SEED)
print('The shape of training dataset: {}'.format(X_train.shape[0]))
print('The shape of testing dataset: {}'.format(X_test.shape[0]))

# Fit and predict
np.random.seed(SEED)
ngb = NGBRegressor(n_estimators=40,
                   Base=default_tree_learner, Dist=Normal, Score=MLE).fit(X_train, y_train)
y_pred = ngb.predict(X_test)
print('NGBoost: R2 score on testing data: {:.2f}%'.format(100 * r2_score(y_test, y_pred)))

plt.plot( y_test, color="black", linestyle="-", linewidth=1, label="Actual" )
plt.plot( y_pred, color="red", linestyle=":", linewidth=1, label="Predicted mean" )
plt.plot(y_pred - 1.96 * y_pred.scale, color="black", linestyle="--", linewidth=0.3, label="95\% prediction interval" )
plt.plot( y_pred + 1.96 * y_pred.scale, color="black", linestyle="--", linewidth=0.3 )

plt.ylim([-75, 75])

plt.xlabel("$x$")

plt.ylabel("$y$")
plt.legend(loc="upper left")


AttributeError                            Traceback (most recent call last)
<ipython-input-246-9918991448b7> in <module>()
      1 plt.plot( y_test, color="black", linestyle="-", linewidth=1, label="Actual" )
      2 plt.plot( y_pred, color="red", linestyle=":", linewidth=1, label="Predicted mean" )
----> 3 plt.plot(y_pred - 1.96 * y_pred.scale, color="black", linestyle="--", linewidth=0.3, label="95\% prediction interval" )
      4 plt.plot( y_pred + 1.96 * y_pred.scale, color="black", linestyle="--", linewidth=0.3 )
      5 

AttributeError: 'numpy.ndarray' object has no attribute 'scale

**Comment by Shafi2016** [comment]
Sorry I found my mistake it should have been instead as y_pred = ngb.pred_dist(X_test)
y_pred.scale

**Comment by tonyduan** [comment]
Sure glad you figured it out.

**Comment by Shafi2016** [comment]
I have two more questions: 

How to improve the model performance. As we do not have lots of parameters as we do in XGBoost or LightGBM if I am not wrong. (https://github.com/stanfordmlgroup/ngboost/blob/master/ngboost/api.py)
In my case I am using the following:
ngb = NGBRegressor(n_estimators=40000,learning_rate =0.09,minibatch_frac=1,tol=0.0009,random_state=22,natural_gradient=True,
                   Base=default_tree_learner, Dist=Normal, Score=MLE).fit(X_train, y_train)
Also when I add "col_sample" I get the following error
"TypeError: __init__() got an unexpected keyword argument 'col_sample" 

Lastly, if you can refer me to code for making probability distributions.

**Comment by tonyduan** [comment]
@Shafi2016 The `col_sample` error should be fixed if you upgrade to the version of NGBoost on GitHub. Run the following and see if it fixes things:
`pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost.git`

The predicted distributions can be created using `ngb.pred_dist` and these objects are just SciPy distributions. For details/examples see our user guide: https://stanfordmlgroup.github.io/ngboost.

**Comment by Shafi2016** [comment]
Thanks, a lot: It worked.
