### ISSUE TITLE
Pass pandas dataframe into fit function

### ISSUE THREAD

**Issue by olkurinnoy** [stanfordmlgroup/ngboost#94]
I'm getting error when I try to pass pandas dataframe X into fit.
As I see only numpy arrays can be passed now because of indexing in sample function
`return idxs, col_idx, X[idxs, :][:, col_idx], Y[idxs], params[idxs, :]`
 that rises error for pandas.
In earlier versions (before 27f3897e3723baf80e51aeeac6fbc155cd5c86f5 commit) for minibatch_frac = 1.0 it worked
`if self.minibatch_frac == 1.0:
            return np.arange(len(Y)), X, Y, params`
but after it couldn't make fit even for default params.
Is it planned to make pandas support?
Thanks!

**Comment by alejandroschuler** [comment]
That's correct- we don't support pandas dataframes. The reason is that if we were to support pandas, we would have to make some choices about how to handle different kinds of data types, e.g. categorical, date-time, etc. that can reside in a pandas dataframe. Depending on the application, whatever way we handle it might not be the best way to do it, and the user may not even be aware that what we do under the hood isn't what they wanted. For that reason we leave it up to the user to decide how these variables should be converted to numeric data using standard tools like pandas or sklearn pipelines, and we enforce this by only accepting numpy arrays as input.

If you have specific suggestions for reasonable defauls (e.g. one-hot encode all categoricals) that would be robust to any kind of data a user could pass in, or if you can point to other python packages that have handled this issue in a way that addresses my concerns, I'd be happy to consider that. I'll close the issue for now but feel free to continue the conversation and I will reopen it if we decide to implement something.

**Comment by olkurinnoy** [comment]
@alejandroschuler Thank you for quick and comprehensive response!
Now I see that it was design solution, I asked this question because many libs (e.g. classifiers in sklearn) supports pandas dataframes without non-numerical features transform.
For now I don't have specific propositions about handling such features, if I have really good ideas I'll inform you but for now I don't want to waste your time.
Thank you again!

**Comment by alejandroschuler** [comment]
No problem, not at all a waste of time! Let me know if/when you find out how those libraries handle this issue.

**Comment by alejandroschuler** [comment]
@olkurinnoy just a heads up that this is now a feature we support! #129

**Comment by olkurinnoy** [comment]
@alejandroschuler Great news, thanks!!
